
//IMPORTANTE: DADO QUE ESTO ES UN LABORATORIO EN EL CUAL SE EXAMINA A LOS ALUMNOS, EL
//CÓDIGO NO ESTARÁ DOCUMENTADO POR RAZONES OBVIAS

//#ifndef DEFINE_H_INCLUDED
//#define DEFINE_H_INCLUDED

#define FALSE 0
#define TRUE 1
#define LST_NO_INI 2
#define LST_VAC 3
#define POS_NULA NULL
#define ELE_NULO NULL

#define SIZE 10
//#endif  //DEFINE_H_INCLUDED
